E-commerce Sales Analysis using Pandas

In [1]:
from google.colab import files
uploaded=files.upload()

Saving ecommerce data.xlsx to ecommerce data.xlsx

In [4]:
import pandas as pd
df=pd.read_excel("ecommerce data.xlsx")

In [5]:
df  #information present in excel

,Order_ID,Customer_ID,Date,Product,Category,Price,Quantity,Total_Amount,Payment_Method,City,Rating,Delivery_Days
0,101,C001,2026-05-01,Mobile,Electronics,15000.0,1.0,15000.0,UPI,Bangalore,5.0,2.0
1,102,C002,2026-05-01,T-Shirt,Clothing,500.0,2.0,1000.0,Card,Hyderabad,4.0,4.0
2,103,C003,2026-05-02,Laptop,Electronics,55000.0,1.0,55000.0,UPI,Chennai,5.0,3.0
3,104,C001,2026-05-02,Shoes,Footwear,2000.0,1.0,2000.0,COD,Bangalore,3.0,5.0
4,105,C004,2026-05-03,Headphones,Electronics,2000.0,2.0,4000.0,Card,Mumbai,4.0,2.0
5,106,C005,2026-05-03,Jeans,Clothing,1500.0,1.0,1500.0,UPI,Delhi,5.0,3.0
6,107,C002,2026-05-04,Watch,Accessories,3000.0,1.0,3000.0,Card,Hyderabad,4.0,2.0
7,108,C006,2026-05-04,Tablet,Electronics,20000.0,1.0,20000.0,UPI,Bangalore,5.0,1.0
8,109,C007,2026-05-05,Bag,Accessories,1200.0,1.0,1200.0,COD,Chennai,3.0,6.0
9,110,C003,2026-05-05,Keyboard,Electronics,800.0,2.0,1600.0,UPI,Chennai,4.0,2.0
10,111,C008,2026-05-06,Mouse,Electronics,600.0,2.0,1200.0,UPI,Pune,4.0,2.0
11,112,C009,2026-05-06,Jacket,Clothing,2500.0,1.0,2500.0,Card,Delhi,5.0,4.0
12,113,C010,2026-05-07,Sandals,Footwear,900.0,1.0,900.0,COD,Mumbai,3.0,5.0
13,114,C011,2026-05-07,PowerBank,Electronics,1200.0,2.0,2400.0,UPI,Bangalore,5.0,2.0
14,115,C012,2026-05-08,Saree,Clothing,3500.0,1.0,3500.0,Card,Chennai,4.0,3.0
15,116,C013,2026-05-08,Backpack,Accessories,1800.0,1.0,1800.0,UPI,Hyderabad,4.0,2.0
16,117,C014,2026-05-09,Smartwatch,Electronics,7000.0,1.0,7000.0,UPI,Pune,5.0,1.0
17,118,C015,2026-05-09,Belt,Accessories,700.0,2.0,1400.0,COD,Delhi,3.0,6.0
18,119,C016,2026-05-10,Trousers,Clothing,1600.0,1.0,1600.0,Card,Mumbai,4.0,3.0
19,120,C017,2026-05-10,Earbuds,Electronics,3000.0,1.0,3000.0,UPI,Bangalore,5.0,2.0
20,121,C018,2026-05-11,Sneakers,Footwear,3500.0,1.0,3500.0,UPI,Chennai,5.0,2.0
21,122,C019,2026-05-11,Cap,Accessories,500.0,2.0,1000.0,COD,Pune,3.0,5.0
22,123,C020,2026-05-12,TV,Electronics,40000.0,1.0,40000.0,Card,Delhi,5.0,4.0
23,124,C021,2026-05-12,Shirt,Clothing,1200.0,2.0,2400.0,UPI,Hyderabad,4.0,3.0
24,125,C022,2026-05-13,Slippers,Footwear,400.0,2.0,800.0,COD,Mumbai,3.0,6.0
25,126,C023,2026-05-13,Charger,Electronics,700.0,2.0,1400.0,UPI,Bangalore,4.0,2.0
26,127,C024,2026-05-14,Dress,Clothing,2200.0,1.0,2200.0,Card,Chennai,5.0,3.0
27,128,C025,2026-05-14,Sunglasses,Accessories,1500.0,1.0,1500.0,UPI,Pune,4.0,2.0
28,129,C026,2026-05-15,Laptop Stand,Electronics,1200.0,1.0,1200.0,UPI,Delhi,5.0,2.0
29,130,C027,2026-05-15,Jeans,Clothing,1800.0,1.0,1800.0,Card,Mumbai,4.0,3.0
30,131,C028,2026-05-16,Formal Shoes,Footwear,3000.0,1.0,3000.0,UPI,Bangalore,5.0,2.0
31,132,C029,2026-05-16,Handbag,Accessories,2500.0,1.0,2500.0,COD,Chennai,3.0,5.0
32,133,C030,2026-05-17,Monitor,Electronics,12000.0,1.0,12000.0,Card,Hyderabad,5.0,2.0
33,134,C031,2026-05-17,Kurti,Clothing,1400.0,2.0,2800.0,UPI,Pune,4.0,3.0
34,135,C032,2026-05-18,Socks,Footwear,300.0,3.0,900.0,COD,Delhi,3.0,6.0
35,136,C033,2026-05-18,Bluetooth Speaker,Electronics,2500.0,1.0,2500.0,UPI,Mumbai,5.0,2.0
36,137,C034,2026-05-19,Skirt,Clothing,1300.0,1.0,1300.0,Card,Bangalore,4.0,3.0
37,138,C035,2026-05-19,Wallet,Accessories,800.0,1.0,800.0,UPI,Chennai,4.0,2.0
38,139,C036,2026-05-20,Tablet Cover,Electronics,600.0,2.0,1200.0,UPI,Pune,5.0,2.0
39,140,C037,2026-05-20,Hoodie,Clothing,2000.0,1.0,2000.0,Card,Delhi,5.0,3.0
40,141,C038,2026-05-21,Flip Flops,Footwear,500.0,2.0,1000.0,COD,Mumbai,3.0,5.0
41,142,C039,2026-05-21,Necklace,Accessories,3000.0,1.0,3000.0,UPI,Bangalore,5.0,2.0
42,143,C040,2026-05-22,Printer,Electronics,8000.0,1.0,8000.0,Card,Chennai,4.0,3.0
43,144,C041,2026-05-22,Blazer,Clothing,4000.0,1.0,4000.0,UPI,Hyderabad,5.0,3.0
44,145,C042,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.info()   #Data Understanding

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        45 non-null     int64
 1   Customer_ID     45 non-null     object
 2   Date            44 non-null     datetime64[ns]
 3   Product         44 non-null     object
 4   Category        44 non-null     object
 5   Price           44 non-null     float64
 6   Quantity        44 non-null     float64
 7   Total_Amount    44 non-null     float64
 8   Payment_Method  44 non-null     object
 9   City            44 non-null     object
 10  Rating          44 non-null     float64
 11  Delivery_Days   44 non-null     float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(5)
memory usage: 4.3+ KB

In [7]:
df.describe()  #Data Understanding

,Order_ID,Date,Price,Quantity,Total_Amount,Rating,Delivery_Days
count,45.000000,44,44.000000,44.000000,44.000000,44.000000,44.000000
mean,123.000000,2026-05-11 12:00:00,4970.454545,1.340909,5236.363636,4.227273,3.068182
min,101.000000,2026-05-01 00:00:00,300.000000,1.000000,800.000000,3.000000,1.000000
25%,112.000000,2026-05-06 00:00:00,875.000000,1.000000,1275.000000,4.000000,2.000000
50%,123.000000,2026-05-11 12:00:00,1800.000000,1.000000,2100.000000,4.000000,3.000000
75%,134.000000,2026-05-17 00:00:00,3000.000000,2.000000,3125.000000,5.000000,4.000000
max,145.000000,2026-05-22 00:00:00,55000.000000,3.000000,55000.000000,5.000000,6.000000
std,13.133926,NaN,10297.653369,0.525763,10204.150795,0.773504,1.404275

In [12]:
df.isnull().sum()

Order_ID          0
Customer_ID       0
Date              0
Product           0
Category          0
Price             0
Quantity          0
Total_Amount      0
Payment_Method    0
City              0
Rating            0
Delivery_Days     0
dtype: int64

In [10]:
df=df.dropna()
df

,Order_ID,Customer_ID,Date,Product,Category,Price,Quantity,Total_Amount,Payment_Method,City,Rating,Delivery_Days
0,101,C001,2026-05-01,Mobile,Electronics,15000.0,1.0,15000.0,UPI,Bangalore,5.0,2.0
1,102,C002,2026-05-01,T-Shirt,Clothing,500.0,2.0,1000.0,Card,Hyderabad,4.0,4.0
2,103,C003,2026-05-02,Laptop,Electronics,55000.0,1.0,55000.0,UPI,Chennai,5.0,3.0
3,104,C001,2026-05-02,Shoes,Footwear,2000.0,1.0,2000.0,COD,Bangalore,3.0,5.0
4,105,C004,2026-05-03,Headphones,Electronics,2000.0,2.0,4000.0,Card,Mumbai,4.0,2.0
5,106,C005,2026-05-03,Jeans,Clothing,1500.0,1.0,1500.0,UPI,Delhi,5.0,3.0
6,107,C002,2026-05-04,Watch,Accessories,3000.0,1.0,3000.0,Card,Hyderabad,4.0,2.0
7,108,C006,2026-05-04,Tablet,Electronics,20000.0,1.0,20000.0,UPI,Bangalore,5.0,1.0
8,109,C007,2026-05-05,Bag,Accessories,1200.0,1.0,1200.0,COD,Chennai,3.0,6.0
9,110,C003,2026-05-05,Keyboard,Electronics,800.0,2.0,1600.0,UPI,Chennai,4.0,2.0
10,111,C008,2026-05-06,Mouse,Electronics,600.0,2.0,1200.0,UPI,Pune,4.0,2.0
11,112,C009,2026-05-06,Jacket,Clothing,2500.0,1.0,2500.0,Card,Delhi,5.0,4.0
12,113,C010,2026-05-07,Sandals,Footwear,900.0,1.0,900.0,COD,Mumbai,3.0,5.0
13,114,C011,2026-05-07,PowerBank,Electronics,1200.0,2.0,2400.0,UPI,Bangalore,5.0,2.0
14,115,C012,2026-05-08,Saree,Clothing,3500.0,1.0,3500.0,Card,Chennai,4.0,3.0
15,116,C013,2026-05-08,Backpack,Accessories,1800.0,1.0,1800.0,UPI,Hyderabad,4.0,2.0
16,117,C014,2026-05-09,Smartwatch,Electronics,7000.0,1.0,7000.0,UPI,Pune,5.0,1.0
17,118,C015,2026-05-09,Belt,Accessories,700.0,2.0,1400.0,COD,Delhi,3.0,6.0
18,119,C016,2026-05-10,Trousers,Clothing,1600.0,1.0,1600.0,Card,Mumbai,4.0,3.0
19,120,C017,2026-05-10,Earbuds,Electronics,3000.0,1.0,3000.0,UPI,Bangalore,5.0,2.0
20,121,C018,2026-05-11,Sneakers,Footwear,3500.0,1.0,3500.0,UPI,Chennai,5.0,2.0
21,122,C019,2026-05-11,Cap,Accessories,500.0,2.0,1000.0,COD,Pune,3.0,5.0
22,123,C020,2026-05-12,TV,Electronics,40000.0,1.0,40000.0,Card,Delhi,5.0,4.0
23,124,C021,2026-05-12,Shirt,Clothing,1200.0,2.0,2400.0,UPI,Hyderabad,4.0,3.0
24,125,C022,2026-05-13,Slippers,Footwear,400.0,2.0,800.0,COD,Mumbai,3.0,6.0
25,126,C023,2026-05-13,Charger,Electronics,700.0,2.0,1400.0,UPI,Bangalore,4.0,2.0
26,127,C024,2026-05-14,Dress,Clothing,2200.0,1.0,2200.0,Card,Chennai,5.0,3.0
27,128,C025,2026-05-14,Sunglasses,Accessories,1500.0,1.0,1500.0,UPI,Pune,4.0,2.0
28,129,C026,2026-05-15,Laptop Stand,Electronics,1200.0,1.0,1200.0,UPI,Delhi,5.0,2.0
29,130,C027,2026-05-15,Jeans,Clothing,1800.0,1.0,1800.0,Card,Mumbai,4.0,3.0
30,131,C028,2026-05-16,Formal Shoes,Footwear,3000.0,1.0,3000.0,UPI,Bangalore,5.0,2.0
31,132,C029,2026-05-16,Handbag,Accessories,2500.0,1.0,2500.0,COD,Chennai,3.0,5.0
32,133,C030,2026-05-17,Monitor,Electronics,12000.0,1.0,12000.0,Card,Hyderabad,5.0,2.0
33,134,C031,2026-05-17,Kurti,Clothing,1400.0,2.0,2800.0,UPI,Pune,4.0,3.0
34,135,C032,2026-05-18,Socks,Footwear,300.0,3.0,900.0,COD,Delhi,3.0,6.0
35,136,C033,2026-05-18,Bluetooth Speaker,Electronics,2500.0,1.0,2500.0,UPI,Mumbai,5.0,2.0
36,137,C034,2026-05-19,Skirt,Clothing,1300.0,1.0,1300.0,Card,Bangalore,4.0,3.0
37,138,C035,2026-05-19,Wallet,Accessories,800.0,1.0,800.0,UPI,Chennai,4.0,2.0
38,139,C036,2026-05-20,Tablet Cover,Electronics,600.0,2.0,1200.0,UPI,Pune,5.0,2.0
39,140,C037,2026-05-20,Hoodie,Clothing,2000.0,1.0,2000.0,Card,Delhi,5.0,3.0
40,141,C038,2026-05-21,Flip Flops,Footwear,500.0,2.0,1000.0,COD,Mumbai,3.0,5.0
41,142,C039,2026-05-21,Necklace,Accessories,3000.0,1.0,3000.0,UPI,Bangalore,5.0,2.0
42,143,C040,2026-05-22,Printer,Electronics,8000.0,1.0,8000.0,Card,Chennai,4.0,3.0
43,144,C041,2026-05-22,Blazer,Clothing,4000.0,1.0,4000.0,UPI,Hyderabad,5.0,3.0

In [14]:
df["Total_Amount"] = df["Price"] * df["Quantity"]
df

,Order_ID,Customer_ID,Date,Product,Category,Price,Quantity,Total_Amount,Payment_Method,City,Rating,Delivery_Days
0,101,C001,2026-05-01,Mobile,Electronics,15000.0,1.0,15000.0,UPI,Bangalore,5.0,2.0
1,102,C002,2026-05-01,T-Shirt,Clothing,500.0,2.0,1000.0,Card,Hyderabad,4.0,4.0
2,103,C003,2026-05-02,Laptop,Electronics,55000.0,1.0,55000.0,UPI,Chennai,5.0,3.0
3,104,C001,2026-05-02,Shoes,Footwear,2000.0,1.0,2000.0,COD,Bangalore,3.0,5.0
4,105,C004,2026-05-03,Headphones,Electronics,2000.0,2.0,4000.0,Card,Mumbai,4.0,2.0
5,106,C005,2026-05-03,Jeans,Clothing,1500.0,1.0,1500.0,UPI,Delhi,5.0,3.0
6,107,C002,2026-05-04,Watch,Accessories,3000.0,1.0,3000.0,Card,Hyderabad,4.0,2.0
7,108,C006,2026-05-04,Tablet,Electronics,20000.0,1.0,20000.0,UPI,Bangalore,5.0,1.0
8,109,C007,2026-05-05,Bag,Accessories,1200.0,1.0,1200.0,COD,Chennai,3.0,6.0
9,110,C003,2026-05-05,Keyboard,Electronics,800.0,2.0,1600.0,UPI,Chennai,4.0,2.0
10,111,C008,2026-05-06,Mouse,Electronics,600.0,2.0,1200.0,UPI,Pune,4.0,2.0
11,112,C009,2026-05-06,Jacket,Clothing,2500.0,1.0,2500.0,Card,Delhi,5.0,4.0
12,113,C010,2026-05-07,Sandals,Footwear,900.0,1.0,900.0,COD,Mumbai,3.0,5.0
13,114,C011,2026-05-07,PowerBank,Electronics,1200.0,2.0,2400.0,UPI,Bangalore,5.0,2.0
14,115,C012,2026-05-08,Saree,Clothing,3500.0,1.0,3500.0,Card,Chennai,4.0,3.0
15,116,C013,2026-05-08,Backpack,Accessories,1800.0,1.0,1800.0,UPI,Hyderabad,4.0,2.0
16,117,C014,2026-05-09,Smartwatch,Electronics,7000.0,1.0,7000.0,UPI,Pune,5.0,1.0
17,118,C015,2026-05-09,Belt,Accessories,700.0,2.0,1400.0,COD,Delhi,3.0,6.0
18,119,C016,2026-05-10,Trousers,Clothing,1600.0,1.0,1600.0,Card,Mumbai,4.0,3.0
19,120,C017,2026-05-10,Earbuds,Electronics,3000.0,1.0,3000.0,UPI,Bangalore,5.0,2.0
20,121,C018,2026-05-11,Sneakers,Footwear,3500.0,1.0,3500.0,UPI,Chennai,5.0,2.0
21,122,C019,2026-05-11,Cap,Accessories,500.0,2.0,1000.0,COD,Pune,3.0,5.0
22,123,C020,2026-05-12,TV,Electronics,40000.0,1.0,40000.0,Card,Delhi,5.0,4.0
23,124,C021,2026-05-12,Shirt,Clothing,1200.0,2.0,2400.0,UPI,Hyderabad,4.0,3.0
24,125,C022,2026-05-13,Slippers,Footwear,400.0,2.0,800.0,COD,Mumbai,3.0,6.0
25,126,C023,2026-05-13,Charger,Electronics,700.0,2.0,1400.0,UPI,Bangalore,4.0,2.0
26,127,C024,2026-05-14,Dress,Clothing,2200.0,1.0,2200.0,Card,Chennai,5.0,3.0
27,128,C025,2026-05-14,Sunglasses,Accessories,1500.0,1.0,1500.0,UPI,Pune,4.0,2.0
28,129,C026,2026-05-15,Laptop Stand,Electronics,1200.0,1.0,1200.0,UPI,Delhi,5.0,2.0
29,130,C027,2026-05-15,Jeans,Clothing,1800.0,1.0,1800.0,Card,Mumbai,4.0,3.0
30,131,C028,2026-05-16,Formal Shoes,Footwear,3000.0,1.0,3000.0,UPI,Bangalore,5.0,2.0
31,132,C029,2026-05-16,Handbag,Accessories,2500.0,1.0,2500.0,COD,Chennai,3.0,5.0
32,133,C030,2026-05-17,Monitor,Electronics,12000.0,1.0,12000.0,Card,Hyderabad,5.0,2.0
33,134,C031,2026-05-17,Kurti,Clothing,1400.0,2.0,2800.0,UPI,Pune,4.0,3.0
34,135,C032,2026-05-18,Socks,Footwear,300.0,3.0,900.0,COD,Delhi,3.0,6.0
35,136,C033,2026-05-18,Bluetooth Speaker,Electronics,2500.0,1.0,2500.0,UPI,Mumbai,5.0,2.0
36,137,C034,2026-05-19,Skirt,Clothing,1300.0,1.0,1300.0,Card,Bangalore,4.0,3.0
37,138,C035,2026-05-19,Wallet,Accessories,800.0,1.0,800.0,UPI,Chennai,4.0,2.0
38,139,C036,2026-05-20,Tablet Cover,Electronics,600.0,2.0,1200.0,UPI,Pune,5.0,2.0
39,140,C037,2026-05-20,Hoodie,Clothing,2000.0,1.0,2000.0,Card,Delhi,5.0,3.0
40,141,C038,2026-05-21,Flip Flops,Footwear,500.0,2.0,1000.0,COD,Mumbai,3.0,5.0
41,142,C039,2026-05-21,Necklace,Accessories,3000.0,1.0,3000.0,UPI,Bangalore,5.0,2.0
42,143,C040,2026-05-22,Printer,Electronics,8000.0,1.0,8000.0,Card,Chennai,4.0,3.0
43,144,C041,2026-05-22,Blazer,Clothing,4000.0,1.0,4000.0,UPI,Hyderabad,5.0,3.0

**ANALYSIS PART**

CALUCLATING THE TOTAL REVENUE

In [15]:
df['Total_Amount'].sum()

np.float64(230400.0)

CHECKING TOP PRODUCTS

In [17]:
df.groupby("Product")["Quantity"].sum().sort_values(ascending=False)

Product
Socks                3.0
Cap                  2.0
Belt                 2.0
Flip Flops           2.0
Shirt                2.0
Mouse                2.0
PowerBank            2.0
Kurti                2.0
Keyboard             2.0
Headphones           2.0
Charger              2.0
T-Shirt              2.0
Slippers             2.0
Tablet Cover         2.0
Jeans                2.0
Bluetooth Speaker    1.0
Bag                  1.0
Backpack             1.0
Blazer               1.0
Formal Shoes         1.0
Earbuds              1.0
Dress                1.0
Mobile               1.0
Laptop               1.0
Handbag              1.0
Jacket               1.0
Hoodie               1.0
Sandals              1.0
Printer              1.0
Necklace             1.0
Monitor              1.0
Laptop Stand         1.0
Shoes                1.0
Skirt                1.0
Saree                1.0
Sneakers             1.0
Smartwatch           1.0
TV                   1.0
Sunglasses           1.0
Tablet               1.0
Trousers             1.0
Wallet               1.0
Watch                1.0
Name: Quantity, dtype: float64

Revenue by city

In [22]:
df.groupby("City")["Total_Amount"].sum()

City
Bangalore    51100.0
Chennai      78300.0
Delhi        49500.0
Hyderabad    24200.0
Mumbai       12600.0
Pune         14700.0
Name: Total_Amount, dtype: float64

CHECKING TOP CUSTOMERS BASED ON AMOUNT

In [26]:
df.groupby("Customer_ID")["Total_Amount"].sum().sort_values(ascending=False).head()

Customer_ID
C003    56600.0
C020    40000.0
C006    20000.0
C001    17000.0
C030    12000.0
Name: Total_Amount, dtype: float64

PAYMENT METHOD USAGE

In [29]:
df["Payment_Method"].value_counts()

Payment_Method
UPI     22
Card    13
COD      9
Name: count, dtype: int64

CATEGORY ANALYSIS

In [30]:
df.groupby("Category")["Total_Amount"].sum().sort_values(ascending=False)

Category
Electronics    175500.0
Clothing        26600.0
Accessories     16200.0
Footwear        12100.0
Name: Total_Amount, dtype: float64

TIME-BASED ANALYSIS

In [32]:
df["Date"] = pd.to_datetime(df["Date"])
df

,Order_ID,Customer_ID,Date,Product,Category,Price,Quantity,Total_Amount,Payment_Method,City,Rating,Delivery_Days
0,101,C001,2026-05-01,Mobile,Electronics,15000.0,1.0,15000.0,UPI,Bangalore,5.0,2.0
1,102,C002,2026-05-01,T-Shirt,Clothing,500.0,2.0,1000.0,Card,Hyderabad,4.0,4.0
2,103,C003,2026-05-02,Laptop,Electronics,55000.0,1.0,55000.0,UPI,Chennai,5.0,3.0
3,104,C001,2026-05-02,Shoes,Footwear,2000.0,1.0,2000.0,COD,Bangalore,3.0,5.0
4,105,C004,2026-05-03,Headphones,Electronics,2000.0,2.0,4000.0,Card,Mumbai,4.0,2.0
5,106,C005,2026-05-03,Jeans,Clothing,1500.0,1.0,1500.0,UPI,Delhi,5.0,3.0
6,107,C002,2026-05-04,Watch,Accessories,3000.0,1.0,3000.0,Card,Hyderabad,4.0,2.0
7,108,C006,2026-05-04,Tablet,Electronics,20000.0,1.0,20000.0,UPI,Bangalore,5.0,1.0
8,109,C007,2026-05-05,Bag,Accessories,1200.0,1.0,1200.0,COD,Chennai,3.0,6.0
9,110,C003,2026-05-05,Keyboard,Electronics,800.0,2.0,1600.0,UPI,Chennai,4.0,2.0
10,111,C008,2026-05-06,Mouse,Electronics,600.0,2.0,1200.0,UPI,Pune,4.0,2.0
11,112,C009,2026-05-06,Jacket,Clothing,2500.0,1.0,2500.0,Card,Delhi,5.0,4.0
12,113,C010,2026-05-07,Sandals,Footwear,900.0,1.0,900.0,COD,Mumbai,3.0,5.0
13,114,C011,2026-05-07,PowerBank,Electronics,1200.0,2.0,2400.0,UPI,Bangalore,5.0,2.0
14,115,C012,2026-05-08,Saree,Clothing,3500.0,1.0,3500.0,Card,Chennai,4.0,3.0
15,116,C013,2026-05-08,Backpack,Accessories,1800.0,1.0,1800.0,UPI,Hyderabad,4.0,2.0
16,117,C014,2026-05-09,Smartwatch,Electronics,7000.0,1.0,7000.0,UPI,Pune,5.0,1.0
17,118,C015,2026-05-09,Belt,Accessories,700.0,2.0,1400.0,COD,Delhi,3.0,6.0
18,119,C016,2026-05-10,Trousers,Clothing,1600.0,1.0,1600.0,Card,Mumbai,4.0,3.0
19,120,C017,2026-05-10,Earbuds,Electronics,3000.0,1.0,3000.0,UPI,Bangalore,5.0,2.0
20,121,C018,2026-05-11,Sneakers,Footwear,3500.0,1.0,3500.0,UPI,Chennai,5.0,2.0
21,122,C019,2026-05-11,Cap,Accessories,500.0,2.0,1000.0,COD,Pune,3.0,5.0
22,123,C020,2026-05-12,TV,Electronics,40000.0,1.0,40000.0,Card,Delhi,5.0,4.0
23,124,C021,2026-05-12,Shirt,Clothing,1200.0,2.0,2400.0,UPI,Hyderabad,4.0,3.0
24,125,C022,2026-05-13,Slippers,Footwear,400.0,2.0,800.0,COD,Mumbai,3.0,6.0
25,126,C023,2026-05-13,Charger,Electronics,700.0,2.0,1400.0,UPI,Bangalore,4.0,2.0
26,127,C024,2026-05-14,Dress,Clothing,2200.0,1.0,2200.0,Card,Chennai,5.0,3.0
27,128,C025,2026-05-14,Sunglasses,Accessories,1500.0,1.0,1500.0,UPI,Pune,4.0,2.0
28,129,C026,2026-05-15,Laptop Stand,Electronics,1200.0,1.0,1200.0,UPI,Delhi,5.0,2.0
29,130,C027,2026-05-15,Jeans,Clothing,1800.0,1.0,1800.0,Card,Mumbai,4.0,3.0
30,131,C028,2026-05-16,Formal Shoes,Footwear,3000.0,1.0,3000.0,UPI,Bangalore,5.0,2.0
31,132,C029,2026-05-16,Handbag,Accessories,2500.0,1.0,2500.0,COD,Chennai,3.0,5.0
32,133,C030,2026-05-17,Monitor,Electronics,12000.0,1.0,12000.0,Card,Hyderabad,5.0,2.0
33,134,C031,2026-05-17,Kurti,Clothing,1400.0,2.0,2800.0,UPI,Pune,4.0,3.0
34,135,C032,2026-05-18,Socks,Footwear,300.0,3.0,900.0,COD,Delhi,3.0,6.0
35,136,C033,2026-05-18,Bluetooth Speaker,Electronics,2500.0,1.0,2500.0,UPI,Mumbai,5.0,2.0
36,137,C034,2026-05-19,Skirt,Clothing,1300.0,1.0,1300.0,Card,Bangalore,4.0,3.0
37,138,C035,2026-05-19,Wallet,Accessories,800.0,1.0,800.0,UPI,Chennai,4.0,2.0
38,139,C036,2026-05-20,Tablet Cover,Electronics,600.0,2.0,1200.0,UPI,Pune,5.0,2.0
39,140,C037,2026-05-20,Hoodie,Clothing,2000.0,1.0,2000.0,Card,Delhi,5.0,3.0
40,141,C038,2026-05-21,Flip Flops,Footwear,500.0,2.0,1000.0,COD,Mumbai,3.0,5.0
41,142,C039,2026-05-21,Necklace,Accessories,3000.0,1.0,3000.0,UPI,Bangalore,5.0,2.0
42,143,C040,2026-05-22,Printer,Electronics,8000.0,1.0,8000.0,Card,Chennai,4.0,3.0
43,144,C041,2026-05-22,Blazer,Clothing,4000.0,1.0,4000.0,UPI,Hyderabad,5.0,3.0

In [34]:
df.groupby("Date")["Total_Amount"].count()

Date
2026-05-01    2
2026-05-02    2
2026-05-03    2
2026-05-04    2
2026-05-05    2
2026-05-06    2
2026-05-07    2
2026-05-08    2
2026-05-09    2
2026-05-10    2
2026-05-11    2
2026-05-12    2
2026-05-13    2
2026-05-14    2
2026-05-15    2
2026-05-16    2
2026-05-17    2
2026-05-18    2
2026-05-19    2
2026-05-20    2
2026-05-21    2
2026-05-22    2
Name: Total_Amount, dtype: int64

In [35]:
df.groupby(df["Date"].dt.month)["Total_Amount"].sum()

Date
5    230400.0
Name: Total_Amount, dtype: float64

In [36]:
df.groupby(df["Date"].dt.month)["Total_Amount"].count()

Date
5    44
Name: Total_Amount, dtype: int64

LOCATION ANALYSIS

In [37]:
df.groupby("City")["Total_Amount"].sum().sort_values(ascending=False)

City
Chennai      78300.0
Bangalore    51100.0
Delhi        49500.0
Hyderabad    24200.0
Pune         14700.0
Mumbai       12600.0
Name: Total_Amount, dtype: float64

In [38]:
df[df["Total_Amount"] > 10000]# High-value orders

,Order_ID,Customer_ID,Date,Product,Category,Price,Quantity,Total_Amount,Payment_Method,City,Rating,Delivery_Days
0,101,C001,2026-05-01,Mobile,Electronics,15000.0,1.0,15000.0,UPI,Bangalore,5.0,2.0
2,103,C003,2026-05-02,Laptop,Electronics,55000.0,1.0,55000.0,UPI,Chennai,5.0,3.0
7,108,C006,2026-05-04,Tablet,Electronics,20000.0,1.0,20000.0,UPI,Bangalore,5.0,1.0
22,123,C020,2026-05-12,TV,Electronics,40000.0,1.0,40000.0,Card,Delhi,5.0,4.0
32,133,C030,2026-05-17,Monitor,Electronics,12000.0,1.0,12000.0,Card,Hyderabad,5.0,2.0

TOP N ANALYSIS

In [40]:
df.sort_values(by="Total_Amount", ascending=False).head(5)

,Order_ID,Customer_ID,Date,Product,Category,Price,Quantity,Total_Amount,Payment_Method,City,Rating,Delivery_Days
2,103,C003,2026-05-02,Laptop,Electronics,55000.0,1.0,55000.0,UPI,Chennai,5.0,3.0
22,123,C020,2026-05-12,TV,Electronics,40000.0,1.0,40000.0,Card,Delhi,5.0,4.0
7,108,C006,2026-05-04,Tablet,Electronics,20000.0,1.0,20000.0,UPI,Bangalore,5.0,1.0
0,101,C001,2026-05-01,Mobile,Electronics,15000.0,1.0,15000.0,UPI,Bangalore,5.0,2.0
32,133,C030,2026-05-17,Monitor,Electronics,12000.0,1.0,12000.0,Card,Hyderabad,5.0,2.0

In [41]:
df.to_excel("final_output.xlsx", index=False)